In [4]:
import numpy as np

In [5]:
X = [[0,0],[1,0],[0,1],[1,1]]
y = [0,1,1,1]

In [6]:
def perc(x):
    f=np.dot(w,x)+b
    if f>=0:
        y=1
    else:
        y=0
    return y

In [7]:
w, b=[0,-1], 0
eta = 0.1

In [8]:
for n in range(100):
    for i in range(4):
        error = y[i]- perc(X[i])
        
        w[0] = w[0] + eta * error * X[i][0]
        w[1] = w[1] + eta * error * X[i][1]
        b = b + eta * error
    
w,b

([0.30000000000000004, 0.19999999999999987], -0.09999999999999998)

In [9]:
perc(X[0]),perc(X[1]),perc(X[2]),perc(X[3])

(0, 1, 1, 1)

In [59]:
import numpy as np
import matplotlib.pyplot as plt

In [60]:
from sklearn import datasets
iris = datasets.load_iris() # 분꽃
iris.target_names # 3종류의 분꽃 분류하기
iris.feature_names # features

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [61]:
X_1=iris.data # input data # the number of input nodes = 4
print(X_1)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [62]:
iris.target_names # setosa = 0, not setosa = 1

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [63]:
y_1=np.where(iris.target>0,1,0)
print(y_1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]


In [64]:
def perc_1(x_1):
    f=np.dot(w_1,x_1)+b_1
    if f>=0:
        y_1=1
    else:
        y_1=0
    return y_1

In [105]:
w_1, b_1=[1,0,1,1], 6
eta = 0.1

In [106]:
pred = []
for n in range(len(X_1)):
    pred.append(perc_1(X_1[n]))
pred = np.array(pred)
pred == y_1

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [107]:
for n in range(100):
    error_sum = 0
    for i in range(len(X_1)):
        error = y_1[i]- perc_1(X_1[i])
        error_sum = error_sum + abs(error)
        
        w_1[0] = w_1[0] + eta * error * X_1[i][0]
        w_1[1] = w_1[1] + eta * error * X_1[i][1]
        w_1[2] = w_1[2] + eta * error * X_1[i][2]
        w_1[3] = w_1[3] + eta * error * X_1[i][3]
        b_1 = b_1 + eta * error
        
    if(error_sum == 0):
        break
    
w_1,b_1,n

([-1.0499999999999998, -1.8100000000000003, 1.5, 1.3399999999999994],
 5.400000000000002,
 5)

In [108]:
pred = []
for n in range(len(X_1)):
    pred.append(perc_1(X_1[n]))
pred = np.array(pred)
pred == y_1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,