In [39]:
import numpy as np

In [40]:
X = np.array([[0,0,1],[1,0,1],[0,1,1],[1,1,1]]) # 세번째 항은 bias
y = np.array([0,1,1,0])

In [69]:
inputs, hiddens, outputs = 3,4,1
np.random.seed(1)
w = np.random.random((3,4)) - 2
omega=np.random.random((4,1))
learning_rate = 0.7

In [70]:
w

array([[-1.582978  , -1.27967551, -1.99988563, -1.69766743],
       [-1.85324411, -1.90766141, -1.81373979, -1.65443927],
       [-1.60323253, -1.46118327, -1.58080549, -1.3147805 ]])

In [71]:
omega

array([[0.20445225],
       [0.87811744],
       [0.02738759],
       [0.67046751]])

In [72]:
def f(x):
    return 1/(1+np.exp(-x))

In [73]:
for i in range(4):
    net_h=np.dot(X[i],w) 
    h = f(net_h)
    net_o=np.dot(h,omega)
    o = f(net_o)
    print(o)

[0.58569433]
[0.52335734]
[0.5172707]
[0.50400321]


In [74]:
delta_h=[1,2,3,7]
for n in range(10000):
    E=0
    for i in range(4):
        net_h=np.dot(X[i],w) 
        h = f(net_h)
        net_o=np.dot(h,omega) 
        o = f(net_o)
        
        E = E + (o-y[i])**2
        delta_o = (o-y[i])*f(net_o)*(1-f(net_o))
        for j in range(4):
            delta_h[j]=delta_o * omega[j] * f(net_h[j]) * (1-f(net_h[j]))
            omega[j]=omega[j] - learning_rate * delta_o * h[j]
            for k in range(3):
                w[k][j]=w[k][j]-learning_rate * delta_h[j]*X[i][k]
E

array([0.00081895])

In [75]:
for i in range(4):
    neth=np.dot(X[i],w) 
    h = f(neth)
    neto=np.dot(h,omega)
    o = f(neto)
    print(o)

[0.01153008]
[0.98662201]
[0.98675466]
[0.01820006]


In [76]:
for i in range(4):
    neth=np.dot(X[i],w)
    h = f(neth)
    neto = np.dot(h,omega)
    o = f(neto)
    
    if o>0.5:
        y_2=1
    else:
        y_2=0 
        
    print(y_2==y[i]) 

True
True
True
True
