In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import torchvision

train_data = torchvision.datasets.MNIST(
    root = 'data',
    train = True,                         
    transform = torchvision.transforms.ToTensor(), 
    download = True,            
)
test_data = torchvision.datasets.MNIST(
    root = 'data', 
    train = False, 
    transform = torchvision.transforms.ToTensor()
)

train_data

test_data # 제출시 이 test 데이터에 대한 정확도를 출력하세요.

Dataset MNIST
    Number of datapoints: 10000
    Root location: data
    Split: Test
    StandardTransform
Transform: ToTensor()

In [2]:
train_data

Dataset MNIST
    Number of datapoints: 60000
    Root location: data
    Split: Train
    StandardTransform
Transform: ToTensor()

In [3]:
test_data

Dataset MNIST
    Number of datapoints: 10000
    Root location: data
    Split: Test
    StandardTransform
Transform: ToTensor()

In [4]:
X = torch.flatten(train_data.data/255, start_dim=1).float()
X

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [18]:
input_size, hidden_sizes, output_size = 28*28, [256,128], 10

In [19]:
model = torch.nn.Sequential(
    torch.nn.Linear(input_size, hidden_sizes[0]),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_sizes[0], hidden_sizes[1]),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_sizes[1], output_size),
    torch.nn.Softmax(dim=1)
)

In [20]:
print(model)

Sequential(
  (0): Linear(in_features=784, out_features=256, bias=True)
  (1): ReLU()
  (2): Linear(in_features=256, out_features=128, bias=True)
  (3): ReLU()
  (4): Linear(in_features=128, out_features=10, bias=True)
  (5): Softmax(dim=1)
)


In [8]:
y = train_data.targets
train_data.targets.size()

torch.Size([60000])

In [9]:
learning_rate = 0.01
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = learning_rate)

In [10]:
nums_epoch = 200
def train(model, criterion, optimizer, nums_epoch, X, y):
    for epoch in range(nums_epoch):
        y_pred = model(X)
        loss = criterion(y_pred,y)
    
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
        if(epoch%5 == 0):
            prediction = y_pred.max(1)[1]
            corrects = (prediction == y)
            accuracy = corrects.sum().float() / float( y.size(0))
            print(epoch, "loss=", loss.item(), "accu=", accuracy.item())

In [11]:
train(model, criterion, optimizer, nums_epoch, X, y)

0 loss= 2.3026974201202393 accu= 0.11423332989215851
5 loss= 1.9008971452713013 accu= 0.6180166602134705
10 loss= 1.6749368906021118 accu= 0.7986500263214111
15 loss= 1.593430757522583 accu= 0.8739333152770996
20 loss= 1.5631884336471558 accu= 0.900783360004425
25 loss= 1.5488955974578857 accu= 0.9139000177383423
30 loss= 1.537419319152832 accu= 0.9253833293914795
35 loss= 1.527522087097168 accu= 0.9350500106811523
40 loss= 1.5199809074401855 accu= 0.9427833557128906
45 loss= 1.5132497549057007 accu= 0.9496999979019165
50 loss= 1.5079418420791626 accu= 0.9549499750137329
55 loss= 1.5033525228500366 accu= 0.9594333171844482
60 loss= 1.4993871450424194 accu= 0.9635999798774719
65 loss= 1.4960334300994873 accu= 0.9668999910354614
70 loss= 1.4933176040649414 accu= 0.9697833061218262
75 loss= 1.4910610914230347 accu= 0.971916675567627
80 loss= 1.4890943765640259 accu= 0.9737499952316284
85 loss= 1.4874308109283447 accu= 0.9751666784286499
90 loss= 1.485974907875061 accu= 0.9765166640281677


In [16]:
y_pred = model(X)
prediction = y_pred.max(1)[1]
prediction

tensor([5, 0, 4,  ..., 5, 6, 8])

In [17]:
y

tensor([5, 0, 4,  ..., 5, 6, 8])